from pydantic import BaseModel, ConfigDict
from typing import Optional
from datetime import datetime, date
from decimal import Decimal

class QuotationBase(BaseModel):
    invoice_code: Optional[str] = None
    brand_name: Optional[str] = None
    status_quotation: Optional[int] = None
    project: Optional[str] = None
    quotation_date: Optional[date] = None
    subtotal: Optional[Decimal] = None
    dpp: Optional[Decimal] = None
    ppn: Optional[Decimal] = None
    grand_total: Optional[Decimal] = None

class QuotationCreate(QuotationBase):
    # quotation_code is auto-generated by the server: QT{YYYYMMDD}{increment}
    brand_name: str
    status_quotation: int

class QuotationUpdate(QuotationBase):
    pass

class QuotationStatusUpdate(BaseModel):
    status_quotation: int

class QuotationResponse(QuotationBase):
    id: int
    quotation_code: str
    invoice_code: Optional[str] = None
    brand_name: str
    status_quotation: int
    project: Optional[str] = None
    quotation_date: Optional[date] = None
    subtotal: Optional[Decimal] = None
    dpp: Optional[Decimal] = None
    ppn: Optional[Decimal] = None
    grand_total: Optional[Decimal] = None
    created_dt: Optional[datetime] = None
    created_by: Optional[str] = None
    changed_dt: Optional[datetime] = None
    changed_by: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)
