"""Add Sow table

Revision ID: 374dab7e826b
Revises: 8754312475f0
Create Date: 2026-02-07 22:18:14.402126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '374dab7e826b'
down_revision: Union[str, None] = '8754312475f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_m_sow', sa.Column('sow_nm', sa.String(), nullable=False))
    op.alter_column('tb_m_sow', 'sow_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tb_m_sow', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_sow', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tb_m_sow', 'changed_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_tb_m_sow_sow_id'), 'tb_m_sow', ['sow_id'], unique=False)
    op.drop_column('tb_m_sow', 'sow_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_m_sow', sa.Column('sow_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tb_m_sow_sow_id'), table_name='tb_m_sow')
    op.alter_column('tb_m_sow', 'changed_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tb_m_sow', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tb_m_sow', 'created_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_sow', 'sow_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tb_m_sow', 'sow_nm')
    # ### end Alembic commands ###
