"""add_master_tables_country_city_interest

Revision ID: 8754312475f0
Revises: df0ed53e7fdd
Create Date: 2026-01-30 18:33:52.321327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8754312475f0'
down_revision: Union[str, None] = 'df0ed53e7fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_m_city', sa.Column('city_nm', sa.String(), nullable=False))
    op.create_index(op.f('ix_tb_m_city_city_id'), 'tb_m_city', ['city_id'], unique=False)
    op.create_foreign_key(None, 'tb_m_city', 'tb_m_country', ['country_id'], ['country_id'])
    op.drop_column('tb_m_city', 'city_code')
    op.drop_column('tb_m_city', 'city_name')
    op.add_column('tb_m_country', sa.Column('country_nm', sa.String(), nullable=False))
    op.drop_constraint(op.f('tb_m_country_country_code_key'), 'tb_m_country', type_='unique')
    op.create_index(op.f('ix_tb_m_country_country_id'), 'tb_m_country', ['country_id'], unique=False)
    op.drop_column('tb_m_country', 'country_name')
    op.drop_column('tb_m_country', 'country_code')
    op.add_column('tb_m_interest', sa.Column('interest_nm', sa.String(), nullable=False))
    op.create_index(op.f('ix_tb_m_interest_interest_id'), 'tb_m_interest', ['interest_id'], unique=False)
    op.drop_column('tb_m_interest', 'interest_name')
    op.alter_column('tb_m_social_media', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_social_media', 'changed_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_tb_m_social_media_social_media_id'), 'tb_m_social_media', ['social_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_m_social_media_social_media_id'), table_name='tb_m_social_media')
    op.alter_column('tb_m_social_media', 'changed_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_social_media', 'created_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('tb_m_interest', sa.Column('interest_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tb_m_interest_interest_id'), table_name='tb_m_interest')
    op.drop_column('tb_m_interest', 'interest_nm')
    op.add_column('tb_m_country', sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('tb_m_country', sa.Column('country_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tb_m_country_country_id'), table_name='tb_m_country')
    op.create_unique_constraint(op.f('tb_m_country_country_code_key'), 'tb_m_country', ['country_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('tb_m_country', 'country_nm')
    op.add_column('tb_m_city', sa.Column('city_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tb_m_city', sa.Column('city_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_m_city', type_='foreignkey')
    op.drop_index(op.f('ix_tb_m_city_city_id'), table_name='tb_m_city')
    op.drop_column('tb_m_city', 'city_nm')
    # ### end Alembic commands ###
