"""Add Brand table

Revision ID: ecc6bc526954
Revises: 374dab7e826b
Create Date: 2026-02-07 22:26:56.502076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecc6bc526954'
down_revision: Union[str, None] = '374dab7e826b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_m_brand', sa.Column('brand_nm', sa.String(), nullable=False))
    op.alter_column('tb_m_brand', 'brand_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tb_m_brand', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_brand', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tb_m_brand', 'changed_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_tb_m_brand_brand_id'), 'tb_m_brand', ['brand_id'], unique=False)
    op.drop_column('tb_m_brand', 'brand_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_m_brand', sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tb_m_brand_brand_id'), table_name='tb_m_brand')
    op.alter_column('tb_m_brand', 'changed_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tb_m_brand', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tb_m_brand', 'created_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_brand', 'brand_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tb_m_brand', 'brand_nm')
    # ### end Alembic commands ###
