"""sync_existing_db

Revision ID: f809cde4b132
Revises: 
Create Date: 2026-01-11 21:04:36.084198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f809cde4b132'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tb_m_menu')
    # op.drop_table('tb_m_social_media')
    # op.drop_table('tb_r_login_log')
    # op.drop_table('tb_r_access_menu')
    op.alter_column('tb_m_role', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_role', 'changed_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_tb_m_role_role_id'), 'tb_m_role', ['role_id'], unique=False)
    op.alter_column('tb_m_user', 'token_expiry_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tb_m_user', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_user', 'changed_dt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('tb_m_user_email_key'), 'tb_m_user', type_='unique')
    op.drop_constraint(op.f('tb_m_user_phone_key'), 'tb_m_user', type_='unique')
    op.create_index(op.f('ix_tb_m_user_email'), 'tb_m_user', ['email'], unique=True)
    op.create_index(op.f('ix_tb_m_user_fullname'), 'tb_m_user', ['fullname'], unique=False)
    op.create_index(op.f('ix_tb_m_user_user_id'), 'tb_m_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_tb_m_user_username'), 'tb_m_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_m_user_username'), table_name='tb_m_user')
    op.drop_index(op.f('ix_tb_m_user_user_id'), table_name='tb_m_user')
    op.drop_index(op.f('ix_tb_m_user_fullname'), table_name='tb_m_user')
    op.drop_index(op.f('ix_tb_m_user_email'), table_name='tb_m_user')
    op.create_unique_constraint(op.f('tb_m_user_phone_key'), 'tb_m_user', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tb_m_user_email_key'), 'tb_m_user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('tb_m_user', 'changed_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_user', 'created_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_user', 'token_expiry_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tb_m_role_role_id'), table_name='tb_m_role')
    op.alter_column('tb_m_role', 'changed_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tb_m_role', 'created_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # Tables restoration removed to prevent conflict
    # ### end Alembic commands ###
